### ISSUE TITLE
`Between` should accept more than `Int` and `Symbol`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataAPI.jl#21]
With the new DataFrames `String` indexing, `Between(a::String, b::String)` fails due to the type constraint in `Between` [here](https://github.com/JuliaData/DataAPI.jl/blob/2007174ed93f9464e38e99197e5efb1ca2331ad4/src/DataAPI.jl#L97). 

My understanding is that DataAPI doesn't need to enforce exactly the type signature in this context. It's enough that functions live here to avoid type piracy.

**Comment by pdeffebach** [comment]
Closing this, since I didn't realize it was added in master. Nevermind! DataFrames master currently doesn't pull in DataAPI master, which is what's causing the issue.

**Comment by bkamins** [comment]
DataFrames master depends on DataAPI.jl v 0.1.2 which defines it.
