### ISSUE TITLE
clarify Between

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaData/DataAPI.jl#49]
as given:
```
"""
    Between(first, last)

Select the columns between `first` and `last` from a table.
"""
struct Between{T1 <: Union{Int, Symbol}, T2 <: Union{Int, Symbol}}
    first::T1
    last::T2
end
```

-  "between" may be understood as "through", inclusive of first and last
-  "between" may be understood as "within", exclusive of first and last

if you intend "through", add e.g. `first` and `last` (including both) from a table
if you intend "within",    add e.g. `first` and `last` (excluding both) from a  table

**Comment by bkamins** [comment]
Fixed in https://github.com/JuliaData/DataAPI.jl/commit/5c927b646360cc4d36c575cf9f98e6bada698419. Thank you!
