### ISSUE TITLE
hcat! function

### ISSUE THREAD

**Issue by bkamins** [JuliaData/DataAPI.jl#5]
Following https://github.com/JuliaData/DataFrames.jl/pull/1866#discussion_r303002112 we could consider adding `hcat!` to DataAPI.jl (alternatively we can have it in DataFrames.jl as we currently have).
CC @nalimilan

**Comment by quinnj** [comment]
What other packages want/need `hcat!`?

**Comment by bkamins** [comment]
This was my concern. I am not sure who else needs it.

Simply `DataFrame` can support it as it is a mutable structure that allows adding columns. Majority of other packages assume that column set is fixed so they do not allow `hcat!`.

**Comment by quinnj** [comment]
Ah, well in that case, I'd say we leave it in DataFrames for now until/unless someone else has a need. I think TypedTables.jl could do this with `FlexTable`, @andyferris ?

**Comment by bkamins** [comment]
we dropped the need for `hcat!` in DataFrames.jl so I close this
