### ISSUE TITLE
`fit`, `fit!`, `predict`, and `predict!` functions

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaData/DataAPI.jl#6]
Currently, the `fit`, `fit!`, `predict`, and `predict!` functions live in `StatsBase`.

What do you think about putting the function stubs for those four functions in `DataAPI`?

The generic fallback definitions would continue to live in `StatsBase`.

**Comment by nalimilan** [comment]
Can you describe what would be the advantage of doing that?

**Comment by DilumAluthge** [comment]
It would allow a package developer to add methods to `DataAPI.fit`, `DataAPI.predict`, etc. without needing their package to depend on `StatsBase`.

`StatsBase` has relatively few dependencies, but `DataAPI` has zero dependencies. So it's easier to convince a package developer to take a dependency on `DataAPI` than on `StatsBase`.

**Comment by nalimilan** [comment]
Why not. Though could you give concrete examples?

**Comment by Tokazama** [comment]
I don't currently have a say in any package that would use this, so take this with a grain of salt. It would be nice if the syntax between the machine learning and statistics ecosystems was more homogenous. For example, it would be much easier for users if the syntax across Flux, MLJ, Turing, and JuliaStats was the same. `fit` and `predict` seem especially applicable.

**Comment by Nosferican** [comment]
I thought the plan was for the Statistical Model abstraction to be moved to StatsModels.

**Comment by kleinschmidt** [comment]
DataAPI seems like the wrong place for these interfaces to live though.  On the one hand, I guess there's no downside for adding a few functions like this to DataAPI even if they don't seem universally or directly related to data per se; but on the other hand, I fear a slippery slope which ends with DataAPI really being a kitchen sink API package, which seems counterproductive to me.  Then again, maybe another stats-specific API package would be useful (I think there was some discussion of making just such a lighter weight StatsAPI package, but I could be mis-remembering)...

**Comment by Tokazama** [comment]
I think it makes sense for https://github.com/JuliaStats/StatsBase.jl/blob/master/src/statmodels.jl to move into StatsModels.jl but that may be too big of a change to ask for.

**Comment by kleinschmidt** [comment]
That's still the plan AFAIK, just no one's had the time to sit down and do it.  But it might still be useful to have a lighter API package if you don't need all the formula stuff...

**Comment by ararslan** [comment]
The requested functions now live in [StatsAPI](https://github.com/JuliaStats/StatsAPI.jl).
